# Generated by Django 3.0.3 on 2020-05-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0002_timezones'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=50)),
                ('utc_offset', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'TimeZone',
            },
        ),
        migrations.DeleteModel(
            name='TimeZones',
        ),
    ]
